@ApiURL = http://localhost:5022

###
GET {{ApiURL}}/api/v1/applications
Accept: application/json

###

GET {{ApiURL}}/api/v1/applications/aaaaaaaa-0000-0000-0000-000000000002
Accept: application/json

